// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhzoo4KLEuIMtUdVe5tF0HjrBS7d5xRyc',
    appId: '1:946778946960:web:a8e05353b1498a86f6c715',
    messagingSenderId: '946778946960',
    projectId: 'a2z-studio',
    authDomain: 'a2z-studio.firebaseapp.com',
    storageBucket: 'a2z-studio.firebasestorage.app',
    measurementId: 'G-61Q7EELD8T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXZI3401sTejrdh83lipKOoCiQpmqTvpA',
    appId: '1:946778946960:android:fa6636c4e6f65c5df6c715',
    messagingSenderId: '946778946960',
    projectId: 'a2z-studio',
    storageBucket: 'a2z-studio.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeCYwWyR3rS4cH7ilFMZFMIP3xG1iHrbE',
    appId: '1:946778946960:ios:f47bf8e40f7a14a2f6c715',
    messagingSenderId: '946778946960',
    projectId: 'a2z-studio',
    storageBucket: 'a2z-studio.firebasestorage.app',
    iosBundleId: 'com.studio.studio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeCYwWyR3rS4cH7ilFMZFMIP3xG1iHrbE',
    appId: '1:946778946960:ios:f47bf8e40f7a14a2f6c715',
    messagingSenderId: '946778946960',
    projectId: 'a2z-studio',
    storageBucket: 'a2z-studio.firebasestorage.app',
    iosBundleId: 'com.studio.studio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6qn5biaWFDINj14oqG0csoZMNY5EkZJ0',
    appId: '1:946778946960:web:cff92e271d505f42f6c715',
    messagingSenderId: '946778946960',
    projectId: 'a2z-studio',
    authDomain: 'a2z-studio.firebaseapp.com',
    storageBucket: 'a2z-studio.firebasestorage.app',
    measurementId: 'G-5YN4E2CLQR',
  );

}